### ISSUE TITLE
Get MythicMob 5 name

### ISSUE THREAD

**Issue by kangarko** [xikage/MythicMobs-API-Examples#2]
I am currently using this code to get a name of a MythicMob from its UUID:

![a](https://i.imgur.com/aKIgABF.png)

Do you have any suggestions on upgrading it to work with MythicMobs 5? Saw a lot of classes got changed, how do I get the MythicMob for instance and how do I get its name now?

Thanks so much!
Matej

**Comment by zeshan321** [comment]
Yeah this would be helpful for me as well

**Comment by kangarko** [comment]
Just a note, I don't expect @xikage to hand a finished code, I just need quick tips on doing this directly and I can turn this into reflection calls thereafter, thanks again!

**Comment by kangarko** [comment]
Fixed it. Anyone looking for the code; here's a sample:

<img width="1296" alt="Screenshot 2022-04-03 at 10 48 06" src="https://user-images.githubusercontent.com/1918426/161419714-6ebf40ea-791d-4071-a12e-83630911c857.png">
